/**
 * 🌱 Seed: categorías vacías — agrega productos a Antibióticos, Cardiovascular,
 *     Vitaminas, Dermatología, Gastrointestinal, Respiratorio y Antialérgicos.
 *
 * Uso: cd backend && npx tsx ../database/seeds/seed-categorias-vacias.ts
 *
 * Los precios están basados en el mercado colombiano (Cruz Verde / Farmatodo).
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seed: productos para categorías vacías\n')

  // ── Obtener categorías ─────────────────────────────────
  const cats = await prisma.categoria.findMany({ orderBy: { id: 'asc' } })
  const catMap: Record<string, number> = {}
  for (const c of cats) {
    catMap[c.slug] = c.id
  }

  // ── Productos a agregar ────────────────────────────────
  const productos = [
    // ── Antibióticos (ID 2) ──
    {
      cum: 'AMOXI-01',
      registroInvima: 'INVIMA 2022M-004001',
      nombre: 'AMOXICILINA 500mg Genfar',
      principioActivo: 'AMOXICILINA TRIHIDRATO',
      atc: 'J01CA04',
      descripcionAtc: 'AMOXICILINA',
      titular: 'Genfar S.A.',
      expediente: 'EXP-ANT-001',
      formaFarmaceutica: 'CÁPSULA',
      viaAdministracion: 'ORAL',
      concentracion: '500mg',
      presentacion: 'Caja x 30 cápsulas',
      slug: 'amoxicilina-500mg-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Antibiótico de amplio espectro para infecciones bacterianas.',
      requiereRx: true,
      categoriaId: catMap['antibioticos'],
      precioVenta: 12500,
      stockMinimo: 20,
      estadoCum: 'Activo',
      estadoRegistro: 'Vigente',
      fechaExpedicion: '2022-01-15',
      fechaVencimientoRegistro: '2027-01-15',
      fechaActivoCum: '2022-03-01',
      esMuestraMedica: false,
      alergenos: 'Penicilina',
      advertencias: 'Completar el ciclo de tratamiento aunque haya mejoría. No usar si es alérgico a penicilinas.',
      indicaciones: 'Infecciones del tracto respiratorio, otitis media, sinusitis, infecciones urinarias.',
      contraindicaciones: 'Alergia a penicilinas. Pacientes con mononucleosis infecciosa.',
      reaccionesAdversas: 'Náuseas, diarrea, erupciones cutáneas.',
      interacciones: 'Metotrexato, warfarina, anticonceptivos orales.',
      modoUso: 'Tomar cada 8 horas con alimentos.',
      unidadReferencia: 'CÁPSULA',
      cantidad: '30',
      unidadMedida: 'CÁPSULAS',
      modalidad: 'Venta con fórmula médica',
      ium: 'IUM-AMOXI-001',
    },
    {
      cum: 'AZITRO-001',
      registroInvima: 'INVIMA 2022M-004002',
      nombre: 'AZITROMICINA 500mg MK',
      principioActivo: 'AZITROMICINA',
      atc: 'J01FA10',
      descripcionAtc: 'AZITROMICINA',
      titular: 'MK Pharma',
      expediente: 'EXP-ANT-002',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '500mg',
      presentacion: 'Caja x 3 tabletas',
      slug: 'azitromicina-500mg-mk',
      laboratorio: 'MK Pharma',
      descripcion: 'Antibiótico macrólido para infecciones respiratorias y de piel.',
      requiereRx: true,
      categoriaId: catMap['antibioticos'],
      precioVenta: 18500,
      stockMinimo: 15,
      estadoCum: 'Activo',
      estadoRegistro: 'Vigente',
      fechaExpedicion: '2022-06-10',
      fechaVencimientoRegistro: '2027-06-10',
      fechaActivoCum: '2022-08-01',
      esMuestraMedica: false,
      advertencias: 'Tomar 1 hora antes o 2 horas después de alimentos. Completar ciclo de 3 días.',
      indicaciones: 'Infecciones respiratorias, faringitis estreptocócica, infecciones de piel.',
      contraindicaciones: 'Hipersensibilidad a macrólidos. Insuficiencia hepática severa.',
      reaccionesAdversas: 'Dolor abdominal, diarrea, náuseas.',
      interacciones: 'Antiácidos, warfarina, digoxina.',
      modoUso: 'Tomar 1 tableta al día por 3 días consecutivos.',
      unidadReferencia: 'TABLETA',
      cantidad: '3',
      unidadMedida: 'TABLETAS',
      modalidad: 'Venta con fórmula médica',
      ium: 'IUM-AZITRO-001',
    },
    {
      cum: 'CIPRO-001',
      registroInvima: 'INVIMA 2022M-004003',
      nombre: 'CIPROFLOXACINO 500mg Procaps',
      principioActivo: 'CIPROFLOXACINO',
      atc: 'J01MA02',
      descripcionAtc: 'CIPROFLOXACINO',
      titular: 'Procaps S.A.',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '500mg',
      presentacion: 'Caja x 14 tabletas',
      slug: 'ciprofloxacino-500mg-procaps',
      laboratorio: 'Procaps S.A.',
      descripcion: 'Antibiótico fluoroquinolona de amplio espectro.',
      requiereRx: true,
      categoriaId: catMap['antibioticos'],
      precioVenta: 22300,
      stockMinimo: 15,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Evitar exposición solar durante el tratamiento. Tomar con abundante agua.',
      indicaciones: 'Infecciones urinarias, gastrointestinales, óseas y articulares.',
      contraindicaciones: 'Epilepsia, menores de 18 años, embarazo y lactancia.',
      reaccionesAdversas: 'Náuseas, diarrea, dolor de cabeza, fotosensibilidad.',
      interacciones: 'Antiácidos, teofilina, warfarina, AINEs.',
      modoUso: 'Tomar cada 12 horas, separado 2 horas de antiácidos.',
      unidadReferencia: 'TABLETA',
      cantidad: '14',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-CIPRO-001',
    },

    // ── Cardiovascular (ID 3) ──
    {
      cum: 'LOSART-001',
      registroInvima: 'INVIMA 2021M-005001',
      nombre: 'LOSARTÁN 50mg Genfar',
      principioActivo: 'LOSARTÁN POTÁSICO',
      atc: 'C09CA01',
      descripcionAtc: 'LOSARTÁN',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '50mg',
      presentacion: 'Caja x 30 tabletas',
      slug: 'losartan-50mg-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Antihipertensivo para el control de la presión arterial.',
      requiereRx: true,
      categoriaId: catMap['cardiovascular'],
      precioVenta: 14600,
      stockMinimo: 20,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No usar durante el embarazo. Monitorear función renal y potasio sérico.',
      indicaciones: 'Hipertensión arterial, nefropatía diabética, insuficiencia cardíaca.',
      contraindicaciones: 'Embarazo (2do y 3er trimestre), estenosis de arteria renal bilateral.',
      reaccionesAdversas: 'Mareos, hipotensión, hiperpotasemia, tos seca.',
      interacciones: 'Diuréticos ahorradores de potasio, AINEs, litio.',
      modoUso: 'Tomar 1 tableta al día, con o sin alimentos.',
      unidadReferencia: 'TABLETA',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-LOSART-001',
    },
    {
      cum: 'ENALAP-001',
      registroInvima: 'INVIMA 2021M-005002',
      nombre: 'ENALAPRIL 10mg Genfar',
      principioActivo: 'ENALAPRIL MALEATO',
      atc: 'C09AA02',
      descripcionAtc: 'ENALAPRIL',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '10mg',
      presentacion: 'Caja x 30 tabletas',
      slug: 'enalapril-10mg-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Inhibidor de la ECA para el control de la hipertensión.',
      requiereRx: true,
      categoriaId: catMap['cardiovascular'],
      precioVenta: 12300,
      stockMinimo: 20,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Puede causar mareos al inicio del tratamiento. Suspender si hay angioedema.',
      indicaciones: 'Hipertensión arterial, insuficiencia cardíaca congestiva.',
      contraindicaciones: 'Embarazo, historial de angioedema, estenosis aórtica.',
      reaccionesAdversas: 'Tos seca, mareos, fatiga, hipotensión, hiperpotasemia.',
      interacciones: 'Diuréticos, AINEs, suplementos de potasio, litio.',
      modoUso: 'Tomar 1 tableta al día, preferiblemente a la misma hora.',
      unidadReferencia: 'TABLETA',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-ENALAP-001',
    },
    {
      cum: 'ATENOL-001',
      registroInvima: 'INVIMA 2021M-005003',
      nombre: 'ATENOLOL 50mg MK',
      principioActivo: 'ATENOLOL',
      atc: 'C07AB03',
      descripcionAtc: 'ATENOLOL',
      titular: 'MK Pharma',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '50mg',
      presentacion: 'Caja x 30 tabletas',
      slug: 'atenolol-50mg-mk',
      laboratorio: 'MK Pharma',
      descripcion: 'Betabloqueador cardioselectivo para hipertensión y angina.',
      requiereRx: true,
      categoriaId: catMap['cardiovascular'],
      precioVenta: 10900,
      stockMinimo: 20,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No suspender bruscamente. Reducir dosis gradualmente en 1-2 semanas.',
      indicaciones: 'Hipertensión arterial, angina de pecho, arritmias cardíacas.',
      contraindicaciones: 'Bradicardia severa, bloqueo cardíaco, asma bronquial.',
      reaccionesAdversas: 'Bradicardia, fatiga, extremidades frías, mareos.',
      interacciones: 'Verapamilo, digoxina, insulina, AINEs.',
      modoUso: 'Tomar 1 tableta al día, preferiblemente en la mañana.',
      unidadReferencia: 'TABLETA',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-ATENOL-001',
    },

    // ── Vitaminas (ID 4) ──
    {
      cum: 'VIT-C-EFE',
      registroInvima: 'INVIMA 2023M-006001',
      nombre: 'VITAMINA C 1000mg Efervescente Procaps',
      principioActivo: 'ÁCIDO ASCÓRBICO',
      atc: 'A11GA01',
      descripcionAtc: 'ÁCIDO ASCÓRBICO',
      titular: 'Procaps S.A.',
      formaFarmaceutica: 'TABLETA EFERVESCENTE',
      viaAdministracion: 'ORAL',
      concentracion: '1000mg',
      presentacion: 'Caja x 30 tabletas efervescentes',
      slug: 'vitamina-c-1000mg-efervescente',
      laboratorio: 'Procaps S.A.',
      descripcion: 'Suplemento de vitamina C de alta dosis. Fortalece el sistema inmunológico.',
      requiereRx: false,
      categoriaId: catMap['vitaminas'],
      precioVenta: 22500,
      stockMinimo: 15,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No exceder la dosis diaria recomendada. Puede causar molestias gástricas.',
      indicaciones: 'Prevención y tratamiento de deficiencia de vitamina C. Refuerzo inmunológico.',
      contraindicaciones: 'Insuficiencia renal severa, litiasis renal oxalato-cálcica.',
      reaccionesAdversas: 'Diarrea, náuseas, cólicos abdominales en dosis altas.',
      interacciones: 'Antiácidos con aluminio, warfarina.',
      modoUso: 'Disolver 1 tableta en un vaso de agua. Tomar 1 vez al día.',
      unidadReferencia: 'TABLETA EFERVESCENTE',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-VITC-001',
    },
    {
      cum: 'COMP-B-001',
      registroInvima: 'INVIMA 2023M-006002',
      nombre: 'COMPLEJO B MK 50 Cápsulas',
      principioActivo: 'VITAMINAS DEL COMPLEJO B',
      atc: 'A11EA',
      descripcionAtc: 'COMPLEJO B',
      titular: 'MK Pharma',
      formaFarmaceutica: 'CÁPSULA BLANDA',
      viaAdministracion: 'ORAL',
      concentracion: 'B1 100mg, B6 100mg, B12 100mcg',
      presentacion: 'Frasco x 50 cápsulas blandas',
      slug: 'complejo-b-mk-50-capsulas',
      laboratorio: 'MK Pharma',
      descripcion: 'Fórmula completa del complejo B para el metabolismo energético y sistema nervioso.',
      requiereRx: false,
      categoriaId: catMap['vitaminas'],
      precioVenta: 28700,
      stockMinimo: 10,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Puede causar orina de color amarillo intenso — efecto normal por la B2.',
      indicaciones: 'Deficiencia de vitaminas del complejo B. Fatiga, estrés, neuropatías.',
      contraindicaciones: 'Hipersensibilidad a alguno de los componentes.',
      reaccionesAdversas: 'Orina amarilla, ocasionalmente náuseas.',
      modoUso: 'Tomar 1 cápsula al día con alimentos.',
      unidadReferencia: 'CÁPSULA',
      cantidad: '50',
      unidadMedida: 'CÁPSULAS',
      ium: 'IUM-COMPB-001',
    },
    {
      cum: 'VIT-D3-001',
      registroInvima: 'INVIMA 2023M-006003',
      nombre: 'VITAMINA D3 2000UI Genfar',
      principioActivo: 'COLECALCIFEROL',
      atc: 'A11CC05',
      descripcionAtc: 'COLECALCIFEROL',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'CÁPSULA',
      viaAdministracion: 'ORAL',
      concentracion: '2000 UI',
      presentacion: 'Caja x 30 cápsulas',
      slug: 'vitamina-d3-2000ui-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Suplemento de vitamina D para fortalecimiento óseo e inmunológico.',
      requiereRx: false,
      categoriaId: catMap['vitaminas'],
      precioVenta: 19500,
      stockMinimo: 15,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Consulte a su médico antes de tomar suplementos de vitamina D. No exceder 4000 UI/día.',
      indicaciones: 'Deficiencia de vitamina D. Prevención de osteoporosis. Refuerzo inmunológico.',
      contraindicaciones: 'Hipercalcemia, hipercalciuria.',
      reaccionesAdversas: 'Raramente hipercalcemia en dosis excesivas.',
      modoUso: 'Tomar 1 cápsula al día con alimentos.',
      unidadReferencia: 'CÁPSULA',
      cantidad: '30',
      unidadMedida: 'CÁPSULAS',
      ium: 'IUM-VITD3-001',
    },
    {
      cum: 'MULTI-001',
      registroInvima: 'INVIMA 2023M-006004',
      nombre: 'MULTIVITAMÍNICO COMPLETO 30 Tab',
      principioActivo: 'MULTIVITAMÍNICO + MINERALES',
      atc: 'A11AA01',
      descripcionAtc: 'MULTIVITAMÍNICO CON MINERALES',
      titular: 'Procaps S.A.',
      formaFarmaceutica: 'TABLETA RECUBIERTA',
      viaAdministracion: 'ORAL',
      concentracion: 'Fórmula completa',
      presentacion: 'Caja x 30 tabletas recubiertas',
      slug: 'multivitaminico-completo-30-tab',
      laboratorio: 'Procaps S.A.',
      descripcion: 'Multivitamínico con 13 vitaminas y 9 minerales para el soporte nutricional diario.',
      requiereRx: false,
      categoriaId: catMap['vitaminas'],
      precioVenta: 41500,
      stockMinimo: 10,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Complemento alimenticio — no reemplaza una dieta balanceada. Mantener fuera del alcance de los niños.',
      indicaciones: 'Soporte nutricional diario. Estados de fatiga y convalecencia.',
      contraindicaciones: 'Hipersensibilidad a algún componente.',
      reaccionesAdversas: 'Ocasionalmente molestias gástricas.',
      modoUso: 'Tomar 1 tableta al día con alimentos.',
      unidadReferencia: 'TABLETA',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-MULTI-001',
    },

    // ── Dermatología (ID 5) ──
    {
      cum: 'CLOTR-CRE',
      registroInvima: 'INVIMA 2022M-007001',
      nombre: 'CLOTRIMAZOL 1% Crema 30g Genfar',
      principioActivo: 'CLOTRIMAZOL',
      atc: 'D01AC01',
      descripcionAtc: 'CLOTRIMAZOL',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'CREMA',
      viaAdministracion: 'TÓPICA',
      concentracion: '1%',
      presentacion: 'Tubo x 30g',
      slug: 'clotrimazol-1-crema-30g-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Antifúngico de uso tópico para tratamiento de hongos en la piel.',
      requiereRx: false,
      categoriaId: catMap['dermatologia'],
      precioVenta: 9800,
      stockMinimo: 15,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Uso externo exclusivamente. No aplicar en ojos, boca o mucosas.',
      indicaciones: 'Tiñas, candidiasis cutánea, pitiriasis versicolor.',
      contraindicaciones: 'Hipersensibilidad al clotrimazol.',
      reaccionesAdversas: 'Irritación local, ardor, enrojecimiento.',
      modoUso: 'Aplicar una capa delgada sobre la zona afectada 2-3 veces al día.',
      unidadReferencia: 'TUBO',
      cantidad: '30',
      unidadMedida: 'GRAMOS',
      ium: 'IUM-CLOTR-CRE',
    },
    {
      cum: 'HIDRO-CRE',
      registroInvima: 'INVIMA 2022M-007002',
      nombre: 'HIDROCORTISONA 1% Crema 20g',
      principioActivo: 'HIDROCORTISONA ACETATO',
      atc: 'D07AA02',
      descripcionAtc: 'HIDROCORTISONA',
      titular: 'MK Pharma',
      formaFarmaceutica: 'CREMA',
      viaAdministracion: 'TÓPICA',
      concentracion: '1%',
      presentacion: 'Tubo x 20g',
      slug: 'hidrocortisona-1-crema-20g',
      laboratorio: 'MK Pharma',
      descripcion: 'Corticosteroide tópico de baja potencia para aliviar inflamación y picazón.',
      requiereRx: false,
      categoriaId: catMap['dermatologia'],
      precioVenta: 11500,
      stockMinimo: 15,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No usar por más de 7 días sin supervisión médica. No aplicar en heridas abiertas.',
      indicaciones: 'Dermatitis, eczema, picaduras de insectos, alergias cutáneas.',
      contraindicaciones: 'Infecciones cutáneas no tratadas, acné, rosácea.',
      reaccionesAdversas: 'Adelgazamiento de piel con uso prolongado.',
      modoUso: 'Aplicar una fina capa en la zona afectada 2 veces al día.',
      unidadReferencia: 'TUBO',
      cantidad: '20',
      unidadMedida: 'GRAMOS',
      ium: 'IUM-HIDRO-CRE',
    },
    {
      cum: 'BETAM-CRE',
      registroInvima: 'INVIMA 2022M-007003',
      nombre: 'BETAMETASONA 0.05% Crema 30g',
      principioActivo: 'BETAMETASONA DIPROPIONATO',
      atc: 'D07AC01',
      descripcionAtc: 'BETAMETASONA',
      titular: 'Procaps S.A.',
      formaFarmaceutica: 'CREMA',
      viaAdministracion: 'TÓPICA',
      concentracion: '0.05%',
      presentacion: 'Tubo x 30g',
      slug: 'betametasona-005-crema-30g',
      laboratorio: 'Procaps S.A.',
      descripcion: 'Corticosteroide tópico de alta potencia para dermatitis severas.',
      requiereRx: true,
      categoriaId: catMap['dermatologia'],
      precioVenta: 16800,
      stockMinimo: 10,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Uso exclusivo bajo prescripción. No aplicar en rostro, axilas o zona inguinal.',
      indicaciones: 'Psoriasis, dermatitis atópica severa, liquen plano.',
      contraindicaciones: 'Infecciones cutáneas, rosácea, acné.',
      reaccionesAdversas: 'Atrofia cutánea, estrías, telangiectasias con uso prolongado.',
      interacciones: 'Uso concomitante con otros corticoides tópicos.',
      modoUso: 'Aplicar una capa delgada 1-2 veces al día, solo en zonas afectadas.',
      unidadReferencia: 'TUBO',
      cantidad: '30',
      unidadMedida: 'GRAMOS',
      ium: 'IUM-BETAM-CRE',
    },

    // ── Gastrointestinal (ID 6) ──
    {
      cum: 'OMEPR-020',
      registroInvima: 'INVIMA 2021M-008001',
      nombre: 'OMEPRAZOL 20mg Genfar Cápsulas',
      principioActivo: 'OMEPRAZOL',
      atc: 'A02BC01',
      descripcionAtc: 'OMEPRAZOL',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'CÁPSULA',
      viaAdministracion: 'ORAL',
      concentracion: '20mg',
      presentacion: 'Caja x 28 cápsulas',
      slug: 'omeprazol-20mg-genfar-capsulas',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Inhibidor de la bomba de protones para tratamiento de acidez y reflujo.',
      requiereRx: false,
      categoriaId: catMap['gastrointestinal'],
      precioVenta: 15600,
      stockMinimo: 30,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Tomar en ayunas 30-60 min antes del desayuno. No usar por más de 14 días sin indicación.',
      indicaciones: 'Enfermedad por reflujo gastroesofágico, úlcera gástrica y duodenal, dispepsia.',
      contraindicaciones: 'Uso prolongado sin supervisión médica. Hipersensibilidad a omeprazol.',
      reaccionesAdversas: 'Dolor de cabeza, diarrea, dolor abdominal, náuseas.',
      interacciones: 'Clopidogrel, metotrexato, warfarina, fenitoína.',
      modoUso: 'Tomar 1 cápsula en ayunas, 30 minutos antes del desayuno.',
      unidadReferencia: 'CÁPSULA',
      cantidad: '28',
      unidadMedida: 'CÁPSULAS',
      ium: 'IUM-OMEPR-001',
    },
    {
      cum: 'RANIT-150',
      registroInvima: 'INVIMA 2021M-008002',
      nombre: 'RANITIDINA 150mg MK',
      principioActivo: 'RANITIDINA CLORHIDRATO',
      atc: 'A02BA02',
      descripcionAtc: 'RANITIDINA',
      titular: 'MK Pharma',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '150mg',
      presentacion: 'Caja x 30 tabletas',
      slug: 'ranitidina-150mg-mk',
      laboratorio: 'MK Pharma',
      descripcion: 'Antagonista H2 para reducción de ácido gástrico.',
      requiereRx: false,
      categoriaId: catMap['gastrointestinal'],
      precioVenta: 11400,
      stockMinimo: 20,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No usar por más de 14 días sin indicación médica. Consultar si hay dolor abdominal persistente.',
      indicaciones: 'Úlcera duodenal y gástrica, reflujo gastroesofágico, síndrome de Zollinger-Ellison.',
      contraindicaciones: 'Hipersensibilidad, porfiria aguda.',
      reaccionesAdversas: 'Dolor de cabeza, mareos, diarrea, fatiga.',
      interacciones: 'Warfarina, teofilina, fenitoína.',
      modoUso: 'Tomar 1 tableta 2 veces al día con alimentos.',
      unidadReferencia: 'TABLETA',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-RANIT-001',
    },
    {
      cum: 'LOPER-002',
      registroInvima: 'INVIMA 2021M-008003',
      nombre: 'LOPERAMIDA 2mg Genfar',
      principioActivo: 'LOPERAMIDA CLORHIDRATO',
      atc: 'A07DA03',
      descripcionAtc: 'LOPERAMIDA',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '2mg',
      presentacion: 'Caja x 12 tabletas',
      slug: 'loperamida-2mg-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Antidiarreico de acción rápida para control de diarrea aguda.',
      requiereRx: false,
      categoriaId: catMap['gastrointestinal'],
      precioVenta: 5600,
      stockMinimo: 25,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No usar si hay fiebre alta o sangre en heces. Suspender si no hay mejoría en 48h.',
      indicaciones: 'Diarrea aguda inespecífica, diarrea del viajero.',
      contraindicaciones: 'Disentería bacteriana, colitis ulcerosa activa, obstrucción intestinal.',
      reaccionesAdversas: 'Estreñimiento, mareos, dolor abdominal.',
      interacciones: 'Antibióticos, anticolinérgicos.',
      modoUso: 'Tomar 2 tabletas inicialmente, luego 1 después de cada deposición suelta. Máx 8 tabletas/día.',
      unidadReferencia: 'TABLETA',
      cantidad: '12',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-LOPER-001',
    },

    // ── Respiratorio (ID 7) ──
    {
      cum: 'SALBU-INH',
      registroInvima: 'INVIMA 2022M-009001',
      nombre: 'SALBUTAMOL 100mcg Inhalador Genfar',
      principioActivo: 'SALBUTAMOL SULFATO',
      atc: 'R03AC02',
      descripcionAtc: 'SALBUTAMOL',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'AEROSOL',
      viaAdministracion: 'INHALADA',
      concentracion: '100 mcg/inhalación',
      presentacion: 'Inhalador x 200 dosis',
      slug: 'salbutamol-100mcg-inhalador-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Broncodilatador de acción rápida para alivio de crisis asmáticas.',
      requiereRx: true,
      categoriaId: catMap['respiratorio'],
      precioVenta: 32800,
      stockMinimo: 10,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No exceder la dosis prescrita. Buscar ayuda si el alivio dura menos de 3 horas.',
      indicaciones: 'Asma bronquial, EPOC, broncoespasmo.',
      contraindicaciones: 'Hipersensibilidad, taquiarritmias.',
      reaccionesAdversas: 'Temblor, taquicardia, dolor de cabeza, ansiedad.',
      interacciones: 'Betabloqueadores, diuréticos, antidepresivos tricíclicos.',
      modoUso: 'Agitar antes de usar. Inhalar 1-2 puff según necesidad. Máx 8 puff/día.',
      unidadReferencia: 'INHALADOR',
      cantidad: '200',
      unidadMedida: 'DOSIS',
      ium: 'IUM-SALBU-INH',
    },
    {
      cum: 'LORAT-010',
      registroInvima: 'INVIMA 2022M-009002',
      nombre: 'LORATADINA 10mg MK',
      principioActivo: 'LORATADINA',
      atc: 'R06AX13',
      descripcionAtc: 'LORATADINA',
      titular: 'MK Pharma',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '10mg',
      presentacion: 'Caja x 30 tabletas',
      slug: 'loratadina-10mg-mk',
      laboratorio: 'MK Pharma',
      descripcion: 'Antihistamínico no sedante para alivio de síntomas alérgicos respiratorios.',
      requiereRx: false,
      categoriaId: catMap['respiratorio'],
      precioVenta: 8900,
      stockMinimo: 20,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Puede causar sequedad bucal. Tomar una vez al día a la misma hora.',
      indicaciones: 'Rinitis alérgica, urticaria, conjuntivitis alérgica.',
      contraindicaciones: 'Hipersensibilidad a loratadina. Insuficiencia hepática severa.',
      reaccionesAdversas: 'Sequedad bucal, dolor de cabeza, fatiga.',
      interacciones: 'Eritromicina, ketoconazol, cimetidina.',
      modoUso: 'Tomar 1 tableta al día con un vaso de agua.',
      unidadReferencia: 'TABLETA',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-LORAT-001',
    },
    {
      cum: 'BECLA-INH',
      registroInvima: 'INVIMA 2022M-009003',
      nombre: 'BECLOMETASONA 50mcg Inhalador Procaps',
      principioActivo: 'BECLOMETASONA DIPROPIONATO',
      atc: 'R03BA01',
      descripcionAtc: 'BECLOMETASONA',
      titular: 'Procaps S.A.',
      formaFarmaceutica: 'AEROSOL',
      viaAdministracion: 'INHALADA',
      concentracion: '50 mcg/inhalación',
      presentacion: 'Inhalador x 200 dosis',
      slug: 'beclometasona-50mcg-inhalador-procaps',
      laboratorio: 'Procaps S.A.',
      descripcion: 'Corticosteroide inhalado para control de asma y enfermedades respiratorias.',
      requiereRx: true,
      categoriaId: catMap['respiratorio'],
      precioVenta: 45200,
      stockMinimo: 8,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'Enjuagar la boca después de cada uso para prevenir candidiasis oral.',
      indicaciones: 'Asma bronquial persistente, EPOC, rinitis alérgica severa.',
      contraindicaciones: 'Crisis asmática aguda. Hipersensibilidad.',
      reaccionesAdversas: 'Candidiasis orofaríngea, ronquera, irritación de garganta.',
      interacciones: 'Corticoides sistémicos, ketoconazol.',
      modoUso: 'Inhalar 1-2 puff dos veces al día. Enjuagar la boca después de usar.',
      unidadReferencia: 'INHALADOR',
      cantidad: '200',
      unidadMedida: 'DOSIS',
      ium: 'IUM-BECLA-INH',
    },

    // ── Antialérgicos (ID 8) — 1 adicional ──
    {
      cum: 'DESLO-005',
      registroInvima: 'INVIMA 2023M-010001',
      nombre: 'DESLORATADINA 5mg Genfar',
      principioActivo: 'DESLORATADINA',
      atc: 'R06AX27',
      descripcionAtc: 'DESLORATADINA',
      titular: 'Genfar S.A.',
      formaFarmaceutica: 'TABLETA',
      viaAdministracion: 'ORAL',
      concentracion: '5mg',
      presentacion: 'Caja x 30 tabletas',
      slug: 'desloratadina-5mg-genfar',
      laboratorio: 'Genfar S.A.',
      descripcion: 'Antihistamínico de segunda generación no sedante para alergias.',
      requiereRx: false,
      categoriaId: catMap['antialergicos'],
      precioVenta: 18700,
      stockMinimo: 15,
      estadoCum: 'Activo',
      esMuestraMedica: false,
      advertencias: 'No causa somnolencia. Tomar a la misma hora cada día.',
      indicaciones: 'Rinitis alérgica, urticaria crónica idiopática.',
      contraindicaciones: 'Hipersensibilidad a desloratadina. Insuficiencia renal severa.',
      reaccionesAdversas: 'Fatiga, sequedad bucal, dolor de cabeza.',
      interacciones: 'Eritromicina, ketoconazol, fluoxetina.',
      modoUso: 'Tomar 1 tableta al día con alimentos.',
      unidadReferencia: 'TABLETA',
      cantidad: '30',
      unidadMedida: 'TABLETAS',
      ium: 'IUM-DESLO-001',
    },
  ]

  // ── Insertar productos ─────────────────────────────────
  let insertados = 0
  let existentes = 0

  for (const p of productos) {
    const existing = await prisma.producto.findUnique({ where: { cum: p.cum } })
    if (existing) {
      existentes++
      console.log(`  ⏩ Ya existe: ${p.nombre}`)
      continue
    }

    const slugBase = p.slug || p.nombre.toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')

    // Generate a unique slug
    let slug = slugBase
    let slugExists = await prisma.producto.findUnique({ where: { slug } })
    let slugCounter = 1
    while (slugExists) {
      slug = `${slugBase}-${slugCounter}`
      slugExists = await prisma.producto.findUnique({ where: { slug } })
      slugCounter++
    }

    await prisma.producto.create({
      data: {
        ...p,
        slug,
        // Parse date strings
        fechaExpedicion: p.fechaExpedicion ? new Date(p.fechaExpedicion) : null,
        fechaVencimientoRegistro: p.fechaVencimientoRegistro ? new Date(p.fechaVencimientoRegistro) : null,
        fechaActivoCum: p.fechaActivoCum ? new Date(p.fechaActivoCum) : null,
      } as any,
    })

    insertados++
    console.log(`  ✅ Creado: ${p.nombre} — $${p.precioVenta.toLocaleString('es-CO')}`)
  }

  console.log(`\n📊 ${insertados} productos insertados, ${existentes} ya existían`)

  // ── Crear lotes con stock ──────────────────────────────
  if (insertados > 0) {
    console.log('\n📦 Creando lotes de inventario...')

    const sucursales = await prisma.sucursal.findMany({ take: 1 })
    if (sucursales.length === 0) {
      console.log('  ⚠️ No hay sucursales para asociar lotes')
      return
    }
    const sucursalId = sucursales[0].id

    const proveedores = await prisma.proveedor.findMany()
    if (proveedores.length === 0) {
      console.log('  ⚠️ No hay proveedores para asociar lotes')
      return
    }
    const proveedor = proveedores[0]

    const hoy = new Date()
    const en6meses = new Date(hoy); en6meses.setMonth(hoy.getMonth() + 6)
    const en2anos = new Date(hoy); en2anos.setFullYear(hoy.getFullYear() + 2)
    const en90dias = new Date(hoy); en90dias.setDate(hoy.getDate() + 90)
    const en30dias = new Date(hoy); en30dias.setDate(hoy.getDate() + 30)

    const lotesConfig: Array<{
      cum: string
      codigoLote: string
      cantidad: number
      fechaVenc: Date
      precioCompra: number
      sucursal: number
    }> = [
      // Antibióticos
      { cum: 'AMOXI-01', codigoLote: 'L-AMOXI-01', cantidad: 200, fechaVenc: en2anos, precioCompra: 5500, sucursal: sucursalId },
      { cum: 'AZITRO-001', codigoLote: 'L-AZITRO-01', cantidad: 150, fechaVenc: en6meses, precioCompra: 9500, sucursal: sucursalId },
      { cum: 'CIPRO-001', codigoLote: 'L-CIPRO-01', cantidad: 100, fechaVenc: en2anos, precioCompra: 11500, sucursal: sucursalId },
      // Cardiovascular
      { cum: 'LOSART-001', codigoLote: 'L-LOSART-01', cantidad: 250, fechaVenc: en2anos, precioCompra: 6500, sucursal: sucursalId },
      { cum: 'ENALAP-001', codigoLote: 'L-ENALAP-01', cantidad: 200, fechaVenc: en2anos, precioCompra: 5500, sucursal: sucursalId },
      { cum: 'ATENOL-001', codigoLote: 'L-ATENOL-01', cantidad: 200, fechaVenc: en90dias, precioCompra: 5000, sucursal: sucursalId },
      // Vitaminas
      { cum: 'VIT-C-EFE', codigoLote: 'L-VIT-C-01', cantidad: 180, fechaVenc: en6meses, precioCompra: 11000, sucursal: sucursalId },
      { cum: 'COMP-B-001', codigoLote: 'L-COMPB-01', cantidad: 120, fechaVenc: en2anos, precioCompra: 14000, sucursal: sucursalId },
      { cum: 'VIT-D3-001', codigoLote: 'L-VITD3-01', cantidad: 90, fechaVenc: en2anos, precioCompra: 9500, sucursal: sucursalId },
      { cum: 'MULTI-001', codigoLote: 'L-MULTI-01', cantidad: 60, fechaVenc: en6meses, precioCompra: 21000, sucursal: sucursalId },
      // Dermatología
      { cum: 'CLOTR-CRE', codigoLote: 'L-CLOTR-01', cantidad: 100, fechaVenc: en2anos, precioCompra: 4000, sucursal: sucursalId },
      { cum: 'HIDRO-CRE', codigoLote: 'L-HIDRO-01', cantidad: 80, fechaVenc: en2anos, precioCompra: 5200, sucursal: sucursalId },
      { cum: 'BETAM-CRE', codigoLote: 'L-BETAM-01', cantidad: 60, fechaVenc: en6meses, precioCompra: 7500, sucursal: sucursalId },
      // Gastrointestinal
      { cum: 'OMEPR-020', codigoLote: 'L-OMEPR-01', cantidad: 350, fechaVenc: en2anos, precioCompra: 7500, sucursal: sucursalId },
      { cum: 'RANIT-150', codigoLote: 'L-RANIT-01', cantidad: 200, fechaVenc: en2anos, precioCompra: 5000, sucursal: sucursalId },
      { cum: 'LOPER-002', codigoLote: 'L-LOPER-01', cantidad: 200, fechaVenc: en90dias, precioCompra: 2500, sucursal: sucursalId },
      // Respiratorio
      { cum: 'SALBU-INH', codigoLote: 'L-SALBU-01', cantidad: 70, fechaVenc: en90dias, precioCompra: 16000, sucursal: sucursalId },
      { cum: 'LORAT-010', codigoLote: 'L-LORAT-01', cantidad: 150, fechaVenc: en30dias, precioCompra: 3500, sucursal: sucursalId },
      { cum: 'BECLA-INH', codigoLote: 'L-BECLA-01', cantidad: 40, fechaVenc: en2anos, precioCompra: 22000, sucursal: sucursalId },
      // Antialérgicos
      { cum: 'DESLO-005', codigoLote: 'L-DESLO-01', cantidad: 80, fechaVenc: en2anos, precioCompra: 8500, sucursal: sucursalId },
    ]

    let lotesCreados = 0
    for (const l of lotesConfig) {
      const producto = await prisma.producto.findUnique({ where: { cum: l.cum } })
      if (!producto) continue

      await prisma.lote.create({
        data: {
          productoId: producto.id,
          sucursalId: l.sucursal,
          proveedorId: proveedor.id,
          codigoLote: l.codigoLote,
          fechaFabricacion: new Date(),
          fechaVencimiento: l.fechaVenc,
          cantidadInicial: l.cantidad,
          cantidadActual: l.cantidad,
          precioCompra: l.precioCompra,
        },
      })
      lotesCreados++
    }
    console.log(`  ✅ ${lotesCreados} lotes creados con stock disponible`)
  }

  console.log('\n✨ Seed de categorías vacías completado exitosamente!')
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
